---

name: Run python tests using pytest
inputs:
  python-version:
    description: Version of Python to use
    required: true

  bot-ssh-key:
    description: GitHub bot SSH private key
    required: false
    default: ''

  unit-test-directory:
    description: Path to unit tests
    required: false
    default: ''

  integration-test-directory:
    description: Path to integration tests
    required: false
    default: ''

  requirements-file-basename:
    description: Basename of the requirements file
    required: false
    default: requirements.txt

  environment:
    description: environment variables to be passed to pytest
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup Python Environment
      uses: ./actions/py/env

    - name: Install dependencies
      shell: bash -l {0}
      run: python3 -m pip install ".[tests]"

    - name: List dependencies explicitly
      shell: bash -l {0}
      run: python3 -m pip list

    - name: Set Environment Variables
      shell: bash -l {0}
      run: echo "${{ inputs.environment }}" >> $GITHUB_ENV

    - name: Run unit tests
      if: inputs.unit-test-directory != ''
      shell: bash -l {0}
      run: |
        # Explicitly passing the environment below as GITHUB_ENV is not passed to pytest
        python3 -m pytest \
        --cov=src/ --cov-report term --cov-report=xml --cov-append \
        ${{ inputs.unit-test-directory }}

    - name: Run integration tests
      if: inputs.integration-test-directory != ''
      shell: bash -l {0}
      run: |
        python3 -m pytest \
        --cov=src/ --cov-report term --cov-report=xml --cov-append \
        ${{ inputs.integration-test-directory }}

      # - name: Upload coverage report
      #   uses: codecov/codecov-action@v3
