---

name: Publish NPM Package and Git Release
description: Uses today's date and npm version to determine new tag. See README for more detail.
inputs:
  node-version:
    description: Version of Node to use
    required: false
    default: 20.x
  npm-token:
    description: grants access to publish releases to NPM
    required: true
  github-token:
    description: grants access to publish releases to github
    required: true
  verify-tests:
    description: if true, run npm test
    required: false
    default: 'true'
  publish-tag:
    description: Publish tag and release before publishing to NPM
    required: true
    default: 'true'
  package-directory:
    description: |
      Directory containing the package.json file dictating what to publish
    required: false
    default: .
  is-public:
    description: if true, publish to a public NPM repository
    default: 'true'
  registry-url:
    description: NPM registry URL
    required: false
    default: https://registry.npmjs.org
  scope:
    description: Scope to publish under, e.g. "@exabyte-io"
    required: false
    default: ''
  npm-options:
    description: Add options to npm install
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: ${{ inputs.package-directory }}/package-lock.json
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}
        always-auth: true
    - name: Set working directory
      shell: bash -l {0}
      run: cd ${{ inputs.package-directory }}
    - name: Install
      shell: bash -l {0}
      run: cd ${{ inputs.package-directory }} && npm install  ${{ inputs.npm-options }}
    - name: Verify tests
      if: inputs.verify-tests == 'true'
      shell: bash -l {0}
      run: cd ${{ inputs.package-directory }} && npm test

    - name: Configure repository
      uses: ./actions/git/config
      with:
        github-token: ${{ inputs.github-token }}
    - name: Determine git tag
      id: get-tag-name
      uses: ./actions/git/version
      with:
        create-new-tag: ${{ inputs.publish-tag }}
    - name: Publish new git tag and release
      if: inputs.publish-tag == 'true'
      uses: ./actions/git/release
      with:
        github-token: ${{ inputs.github-token }}
        tag-name: ${{ steps.get-tag-name.outputs.tag-name }}

    - name: Prepare npmignore if not specified in package.json
      shell: bash -l {0}
      run: |
        cd ${{ inputs.package-directory }}
        # if package.json specifies what files to pack, skip this step
        FILES=$(jq -r .files package.json)
        if [[ "${FILES}" == "null" ]]; then
            # npm uses .gitignore by default if .npmignore is not present
            # but if .npmignore is present, it will not use .gitignore
            # and we want .npmignore to be a superset of files to ignore
            cat .gitignore >> .npmignore   # if .npmignore not specified, defaults to .gitignore
            cat npmignore >> .npmignore 2>/dev/null  # add real npmignore contents if they exist
            echo "actions/" >> .npmignore  # don't package our composite actions into NPM packages
            echo "!src/actions" >> .npmignore  # include src/dist actions
            echo "!dist/actions" >> .npmignore  # include src/dist actions
            echo ".github/" >> .npmignore  # don't package our project actions either
            echo "token.dat" >> .npmignore # don't ship the github token used for gh CLI
        fi

    - name: Publish release to NPM
      id: publish-release-to-npm
      shell: bash -l {0}
      run: |
        cd ${{ inputs.package-directory }}
        echo "NOTE: REMOVING .npmrc file to enable GH NAMESPACE usage. Use action instead!"
        rm -f .npmrc
        TAG_NAME=${{ steps.get-tag-name.outputs.tag-name }}
        echo "tag name: ${TAG_NAME}"
        echo "tag-name=${TAG_NAME}" >> "$GITHUB_OUTPUT"
        echo "::set-output name=tag-name::$(echo ${TAG_NAME})"
        npm --no-git-tag-version version "${{ steps.get-tag-name.outputs.tag-name }}"
        if [[ "${{ inputs.is-public }}" == "true" ]]; then
          npm publish --access public
        else
          npm publish
        fi
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}

