---

name: Interact with ECR

description: |
  Composite action to pull/push a docker image. By default only output registry.
inputs:
  ecr-repository:
    description: Name of ECR repository
    required: true
  image-tag:
    description: Image tag to push to ECR
    required: true
  aws-access-key-id:
    description: AWS Access Key ID
    required: true
  aws-secret-access-key:
    description: AWS Secret Access Key
    required: true
  action:
    description: Whether to pull or push. If empty, no action is taken
    required: false
    default: ''
  aws-region:
    description: AWS region to use
    required: false
    default: us-west-2
outputs:
  registry:
    description: Name of ECR registry
    value: ${{ steps.login-ecr.outputs.registry }}

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
    - name: Interact with ECR
      shell: bash -l {0}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        COMMAND: ${{ inputs.action }}
      run: |
        if [[ "${COMMAND}" != "" ]]; then
          docker ${COMMAND} ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        fi

