---

name: Set shared variables, pip config for python workflows
inputs:
  pypi-mat3ra-com-user:
    required: false
    default: ''
  pypi-mat3ra-com-password:
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set Environment
      shell: bash -l {0}
      run: sed "" "${{ github.action_path }}/env" >> $GITHUB_ENV
    - name: Set Pip Configuration File
      if: inputs.pypi-mat3ra-com-user != '' && inputs.pypi-mat3ra-com-password != ''
      shell: bash -l {0}
      env:
        PYPI_USER: ${{ inputs.pypi-mat3ra-com-user }}
        PYPI_PASSWORD: ${{ inputs.pypi-mat3ra-com-password }}
      run: |
        # Setup config file
        mkdir -p ~/.pip
        cat "${{ github.action_path }}/pip.conf" >> ~/.pip/pip.conf
        # Setup basic authentication
        cat > ~/.netrc << EOF
        machine pypi.mat3ra.com
        login ${PYPI_USER}
        password ${PYPI_PASSWORD}
        EOF
        chmod 600 ~/.netrc
