---

name: Set shared variables, pip config for python workflows
inputs:
  pypi-mat3ra-com-user:
    required: false
    default: ''
  pypi-mat3ra-com-password:
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set Environment
      shell: bash -l {0}
      run: sed "" ./actions/py/env/env >> $GITHUB_ENV
    - name: Set Pip Configuration File
      if: inputs.pypi-mat3ra-com-user != '' && inputs.pypi-mat3ra-com-password != ''
      shell: bash -l {0}
      run: |
        # Setup config file
        mkdir -p /root/.pip
        cat ./actions/py/env/pip.conf >> ~/.pip/pip.conf
        # Setup basic authentication
        cat > ~/.netrc << EOF
        machine pypi.mat3ra.com
        login ${{ inputs.pypi-mat3ra-com-user }}
        password ${{ inputs.pypi-mat3ra-com-password }}
        EOF
        # Remove leading whitespace (just in case)
        sed -i 's/^[t ]*//g' ~/.netrc
