---

name: Validate JS Packages
inputs:
  package-directory:
    description: Relative directory of the package.json file
    required: false
    default: .

runs:
  using: composite
  steps:
    # yamllint disable rule:line-length
    # See https://stackoverflow.com/questions/23210437/npm-install-private-github-repositories-by-dependency-in-package-json#answer-35892637
    # yamllint enable rule:line-length
    # for more details and git configuration tips for managing this installation pattern
    # TODO : Add eslint --check // prettier --check // test-coverage --check
    # NOTE: we ignore `git+https://github.com/Exabyte-io/simpl-schema`
    - name: Validate package.json
      shell: bash -l {0}
      run: |
        PKG_JSON=${{ inputs.package-directory }}/package.json
        for invalid in "git:" "git+ssh:" "git+http:" "git+https:" "file:"; do
          if grep -v "simpl-schema" ${PKG_JSON} | grep -q "${invalid}"; then
            echo "Found ${invalid} in package.json, please publish upstream package."
            echo "Then update ${{ inputs.package-directory }}/package.json."
            exit 1
          else
            echo "Found no ${invalid} references in package.json"
          fi
        done
    - name: Validate codebase with eslint
      shell: bash -l {0}
      run: |
        npm run lint
