---

name: Validate JS Packages and Codebase
inputs:
  node-version:
    description: Version of Node to use
    required: false
  package-directory:
    description: Relative directory of the package.json file
    required: false
    default: .
  skip-eslint:
    description: Whether to run the eslint action
    required: false
    default: 'false'
  use-npm-ci:
    description: Whether to run the eslint action
    required: false
    default: ''
  use-legacy-peer-deps:
    description: Whether to use legacy peer deps
    required: false
    default: ''


runs:
  using: composite
  steps:
    # yamllint disable rule:line-length
    # See https://stackoverflow.com/questions/23210437/npm-install-private-github-repositories-by-dependency-in-package-json#answer-35892637
    # yamllint enable rule:line-length
    # for more details and git configuration tips for managing this installation pattern
    # TODO : Add eslint --check // prettier --check // test-coverage --check
    # NOTE: we ignore `git+https://github.com/Exabyte-io/simpl-schema`
    - name: Validate package.json
      shell: bash -l {0}
      run: |
        PKG_JSON=${{ inputs.package-directory }}/package.json
        for invalid in "git:" "git+ssh:" "git+http:" "git+https:" "file:"; do
          if grep -v "simpl-schema" ${PKG_JSON} | grep -q "${invalid}"; then
            echo "Found ${invalid} in package.json, please publish upstream package."
            echo "Then update ${{ inputs.package-directory }}/package.json."
            echo "::notice file=${{ inputs.package-directory }}/package.json::Found ${invalid}."
          else
            echo "Found no ${invalid} references in package.json"
          fi
        done
    - name: Setup NodeJS
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: ${{ inputs.node-version }}
    - name: Validate codebase with eslint
      if: inputs.skip-eslint != 'true'
      shell: bash -l {0}
      run: |
        NPM_OPTIONS=""
        if [ "${{ inputs.package-directory }}" != "." ]; then
          NPM_OPTIONS="--prefix ${{ inputs.package-directory }}"
        fi
        if [ ! -z "${{ inputs.use-legacy-peer-deps }}" ]; then
          USE_LEGACY_PEER_DEPS="--legacy-peer-deps"
        fi
        if [ ! -z "${{ inputs.use-npm-ci }}" ]; then
          npm ${NPM_OPTIONS} ci
        else
          npm ${NPM_OPTIONS} install --no-save ${USE_LEGACY_PEER_DEPS}
        fi
        npm ${NPM_OPTIONS} run lint
