---

name: Configure Git Repository
inputs:
  github-token:
    description: grants access to github repository
    required: true
  github-repo:
    description: the name of the repository
    required: false

runs:
  using: composite
  steps:
    - name: Form the Repor URL with Auth.
      shell: bash -l {0}
      run: |
        # configure git repository for downstream interaction
        if [ ! -z "${{ inputs.github-repo }}" ]; then
          REPO_NAME="${{ inputs.github-repo }}"
        else
          REPO_NAME="${{ github.repository }}"
        fi
        REPO_URL=https://${{ inputs.github-token }}@github.com/${REPO_NAME}.git
        echo "ACTIONS_GIT_CONFIG_REPO_URL=${REPO_URL}" >> "$GITHUB_ENV"
    - name: Configure git for bot account
      shell: bash -l {0}
      run: |
        # configure git repository for downstream interaction
        git remote set-url origin ${ACTIONS_GIT_CONFIG_REPO_URL}
        git config user.name "exabyte-io-bot"
        git config user.email "info@exabyte.io"
    - name: Authenticate to github CLI
      shell: bash -l {0}
      run: |
        # configure github cli for automatic release generation
        echo "${{ inputs.github-token }}" > token.dat
        gh auth login --with-token < token.dat
    - name: Fetch git tags
      # Only trigger fetch if setting up for the current repo, not another one
      if: inputs.github-repo == ''
      shell: bash -l {0}
      run: |
        # fetch all git tags for version logic
        # To avoid: `--unshallow on a complete repository does not make sense`
        git fetch --prune --unshallow --tags || git fetch --prune --tags
