---

name: Release to Github
inputs:
  github-token:
    description: grants access to github repository
    required: true
    default: ''
  tag-name:
    description: name of tag to push and release
    required: true
    default: ''
  skip-publish:
    description: whether to only create tag and not publish it
    required: true
    default: ''

runs:
  using: composite
  steps:

    - name: Create git tag
      shell: bash -l {0}
      env:
        TAG_NAME: ${{ inputs.tag-name }}
      run: git tag "${TAG_NAME}"

    - name: Push Tag To Remote
      if: inputs.skip-publish == ''
      shell: bash -l {0}
      env:
        TAG_NAME: ${{ inputs.tag-name }}
      run: |
          git push origin "${TAG_NAME}"
          sleep 15  # give github time to register the tag before publishing

    - name: Create Release
      if: inputs.skip-publish == ''
      shell: bash -l {0}
      env:
        TAG_NAME: ${{ inputs.tag-name }}
      run: |
          NOTES="Release ${TAG_NAME} created by exabyte-io-bot"
          gh release create "${TAG_NAME}" --title "v${TAG_NAME}" --notes "${NOTES}"
