---

name: Release to Github
inputs:
  github-token:
    description: grants access to github repository
    required: true
    default: ''
  tag-name:
    description: name of tag to push and release
    required: true
    default: ''
  sync-branch:
    description: string which if true, will push commits back to branch
    required: true
    default: 'false'

runs:
  using: composite
  steps:

    - name: Sync Branch
      if: inputs.sync-branch == 'true'
      shell: bash -l {0}
      run: git push --force origin ${{ github.ref_name }}

    - name: Push Tag To Remote
      shell: bash -l {0}
      run: |
          git push origin ${{ inputs.tag-name }}
          sleep 15  # give github time to register the tag before publishing

    - name: Create Release
      shell: bash -l {0}
      run: |
          NOTES="Release ${{ inputs.tag-name }} created by exabyte-io-bot"
          gh release create ${{ inputs.tag-name }} --notes "${NOTES}"
