---

name: Validate a Dockerfile
description: Runs minimally hadolint on a given Dockerfile

inputs:
  dockerfile:
    description: path to Dockerfile to lint
    required: true
  checked-out:
    description: whether being used in a downstream repository
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Get path to config
      id: path
      shell: bash -l {0}
      run: |
        CONFIG_PATH=./.hadolint.yml
        if [[ "${{ inputs.checked-out }}" == "true" ]]; then
            CONFIG_PATH=./actions/.hadolint.yml
        fi
        echo "::set-output name=config-path::$(echo ${CONFIG_PATH})"
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
      with:
        dockerfile: ${{ inputs.dockerfile }}
        config: ${{ steps.path.outputs.config-path }}

