---

name: Validate a Dockerfile
description: Runs minimally hadolint on a given Dockerfile

inputs:
  dockerfile:
    description: path to Dockerfile to lint
    required: true
  checked-out:
    description: whether being used in a downstream repository
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Get path to config
      id: path
      shell: bash -l {0}
      run: |
        CONFIG_PATH=./.hadolint.yml
        if [[ "${{ inputs.checked-out }}" == "true" ]]; then
            CONFIG_PATH=./actions/.hadolint.yml
        fi
        echo "config-path=${CONFIG_PATH}" >> "$GITHUB_OUTPUT"
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@2a66e89f53d0771bb131a7fa31f3136336094aa6 # v3.4.0
      with:
        dockerfile: ${{ inputs.dockerfile }}
        config: ${{ steps.path.outputs.config-path }}

