---

name: Lint, Build and Push

on: [push]  # yamllint disable-line rule:truthy

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Installs linter
        run: |
          python -m pip install wheel==0.37.1
          python -m pip install yamllint==1.26.3
      - name: Runs yaml linter
        run: yamllint .
      - name: Runs docker linter
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./docker/build/centos/Dockerfile

  publish-centos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - name: Get ECR registry
        id: login-ecr
        uses: ./docker/ecr
        with:
          ecr-repository: centos-7.9-base
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ECR }}
          image-tag: latest
          action: pull
      - name: Build base CentOS image
        uses: ./docker/build
        with:
          image-name: ${{ steps.login-ecr.outputs.registry }}/centos-7.9-base
          dockerfile: ./docker/build/centos/Dockerfile
      - name: Push base CentOS image to ECR
        uses: ./docker/ecr
        with:
          ecr-repository: centos-7.9-base
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ECR }}
          image-tag: latest
          action: push
