---

name: Lint, Build and Push

on: [push]  # yamllint disable-line rule:truthy

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run yaml linter
        uses: ./yaml/lint
      - name: Run docker linter
        uses: ./docker/validate
        with:
          dockerfile: ./docker/build/centos/Dockerfile
          checked-out: false

  publish-centos:
    runs-on: ubuntu-latest
    # TB disabled the below on 2023-09-18
    if: github.ref_name == 'main' && false
    steps:
      - name: Checkout this repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Get ECR registry
        id: login-ecr
        uses: ./docker/ecr
        with:
          ecr-repository: centos-7.9-base
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ECR }}
          image-tag: latest
          action: pull
      - name: Build base CentOS image
        uses: ./docker/build
        with:
          image-name: ${{ steps.login-ecr.outputs.registry }}/centos-7.9-base
          dockerfile: ./docker/build/centos/Dockerfile
      - name: Push base CentOS image to ECR
        uses: ./docker/ecr
        with:
          ecr-repository: centos-7.9-base
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ECR }}
          image-tag: latest
          action: push
