name: Publish Git Release and Python Package
inputs:
  python-version:
    description: "Version of Python to use"
    required: true
  github-token:
    description: "Grants access to publish releases to github"
    required: true
  pypi-username:
    description: "Username on PyPI"
    required: true
  pypi-password:
    description: "Password of PyPI user"
    required: true
  publish-tag:
    description: "Publish tag and release before publishing to PyPI"
    required: true
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Publish Tag & Release to Github
      if: inputs.publish-tag == 'true'
      uses: ./actions/git/version
      with:
        github-token: ${{ inputs.github-token }}
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
    - name: Build Package
      shell: bash -l {0}
      run: python -m build
    - name: Publish Package
      shell: bash -l {0}
      run: twine upload dist/*
      env:
        TWINE_USERNAME: ${{ inputs.pypi-username }}
        TWINE_PASSWORD: ${{ inputs.pypi-password }}


